spring:
  application:
    name: ecommerce-saas
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: secret

  profiles:
    active: local # default, pode ser sobrescrito com SPRING_PROFILES_ACTIVE

  jackson:
    serialization:
      write-dates-as-timestamps: false

  codec:
    max-in-memory-size: 10MB

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
